---
driver:
  name: ec2
  instance_type: t2.micro
  aws_ssh_key_id: my_aws
  security_group_ids: ["sg-01e23ba9d317036eb"]
  region: us-east-1
  subnet_id: subnet-08bf58a98ae93e879
  ssl_verify_peer: false
  associate_public_ip: false
  private_ip_address: 10.0.1.5
  interface: private_dns
  tags:
    Name: test-kitchen-rhel-base

platforms:
  - name: ubuntu-16.04
    driver:
      image_id: ami-a4dc46db
    transport:
    username: ubuntu

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[ntp::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
